Class {
	#name : 'AILinearRegressionLeastSquaresVanillaTest',
	#superclass : 'AILinearRegressionLeastSquaresTest',
	#category : 'AI-LinearModels-Tests',
	#package : 'AI-LinearModels-Tests'
}

{ #category : 'running' }
AILinearRegressionLeastSquaresVanillaTest >> regression [

	^ AILinearRegressionLeastSquaresVanilla new
]

{ #category : 'tests' }
AILinearRegressionLeastSquaresVanillaTest >> testBiasDerivative [

	self skip
]

{ #category : 'tests' }
AILinearRegressionLeastSquaresVanillaTest >> testCostDerivativeActual [

	self skip
]

{ #category : 'tests' }
AILinearRegressionLeastSquaresVanillaTest >> testWeightedSumOf [

	self skip
]
